x-airflow-common:
  &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  AIRFLOW__CORE__FERNET_KEY: ''
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
  AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
  AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
  AIRFLOW__WEBSERVER__SECRET_KEY: "h9Jk3vG7#sLx2qW8%FpLtY@5ZbM1Xe#p"  

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5

  airflow-init:
    build: .
    depends_on:
      - postgres
    environment:
      <<: *airflow-env
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
    entrypoint: >
      /bin/bash -c "airflow db migrate &&
      airflow users create --username airflow --firstname Chandana --lastname Sreya --role Admin --email test@email.com --password airflow"

  airflow-webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      <<: *airflow-env
    ports:
      - "8082:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt_lab2_music:/opt/airflow/dbt_lab2_music
      - ./logs:/opt/airflow/logs
      - ~/.dbt:/home/airflow/.dbt
    command: webserver

  airflow-scheduler:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      <<: *airflow-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt_lab2_music:/opt/airflow/dbt_lab2_music
      - ./logs:/opt/airflow/logs
      - ~/.dbt:/home/airflow/.dbt
    command: scheduler
  
  superset:
    image: apache/superset:latest
    ports:
      - "8088:8088"
    environment:
      SUPERSET_ENV: production
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_SECRET_KEY: "6bfae2c7d3b047149c9cf327ed52dc74f3da7987c061c5d7f0aa81832e72c84b"
    depends_on:
      - postgres
    volumes:
      - superset_home:/app/superset_home
    command: >
      /bin/sh -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Chandana --lastname Sreya --email test@example.com --password admin123 &&
        superset init &&
        gunicorn --bind 0.0.0.0:8088 'superset.app:create_app()' --workers 3 --timeout 120"

volumes:
  postgres-db-volume:
  superset_home:

