version: 2

models:
  - name: cleaned_spotify
    description: "Cleaned Spotify data from raw top_streamed_songs"
    columns:
      - name: id
        description: "Unique ID"
        tests:
          - not_null
          - unique

      - name: artist_title
        tests:
          - not_null

      - name: year
        tests:
          - not_null

      - name: streams
        tests:
          - not_null


